package com.beancrumbs.processor;

import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Annotation;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * This annotation is used to mark generated classes. 
 * Application can then check wether the class has been generated by BeanCrumbs. 
 * @author alexr
 *
 */
@Retention(RUNTIME)
@Target(TYPE)
public @interface Crumbed {
	/**
	 * Annotation that was used to mark source class. 
	 * @return
	 */
	Class<? extends Annotation> value() default Crumbed.class;
}
